### Data Preporcessing

In [1]:
#Importing the libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#Importing the dataset
dataset = pd.read_csv("events_data_encoded.csv")

In [3]:
dataset.head()

YEAR  MONTH         STATNAME  STATCD     DISTNAME  DISTCD EVENT_NAME  \
0  2013      9        TELANGANA      36  RANGA REDDY    3606  education   
1  2013     11  JAMMU & KASHMIR       1      KUPWARA     101  education   
2  2013     11    UTTAR PRADESH       9    FIROZABAD     916    poverty   
3  2013      5           KERALA      32    KOZHIKODE    3204  education   
4  2013      4  JAMMU & KASHMIR       1        PUNCH     111  donations   

   EVENT_CODE  
0           3  
1           3  
2           1  
3           3  
4           4

In [4]:
dataset.isnull().sum()

YEAR          0
MONTH         0
STATNAME      0
STATCD        0
DISTNAME      0
DISTCD        0
EVENT_NAME    0
EVENT_CODE    0
dtype: int64

In [5]:
#Independent features
X = dataset.iloc[:, [1,5]].values

In [6]:
X

array([[   9, 3606],
       [  11,  101],
       [  11,  916],
       ..., 
       [   6, 2127],
       [   9, 2348],
       [  11, 3303]])

In [7]:
#dependent variable vector
y = dataset.iloc[:, 7].values

In [8]:
y

array([3, 3, 1, ..., 3, 1, 4])

In [9]:
#Encode categorical data

from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0,1])
X = onehotencoder.fit_transform(X).toarray()

In [10]:
df_X = pd.DataFrame(data=X)
df_y = pd.DataFrame(data=y)

In [11]:
df_X

0    1    2    3    4    5    6    7    8    9   ...   632  633  634  \
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
3       0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
4       0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
5       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
6       0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
7       0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
8       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
9       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
10      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
11      0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
12      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
13      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
14      0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
15      0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
16      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
17      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
18      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
19      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
20      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
21      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
22      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
23      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0 ...   0.0  0.0  0.0   
24      0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
25      1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
26      0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
27      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
28      0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
29      0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...   
249970  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249971  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249972  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249973  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249974  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249975  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
249976  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249977  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249978  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249979  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249980  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249981  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0 ...   0.0  0.0  0.0   
249982  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
249983  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249984  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249985  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0 ...   0.0  0.0  0.0   
249986  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249987  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 ...   0.0  0.0  0.0   
249988  

In [12]:
#Splitting the dataset into training and test set

from sklearn.cross_validation import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X, y, test_size=0.2 , random_state=0)

/home/shuja1497/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [13]:
X_train , X_test , y_train , y_test

(array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]]),
 array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  1., ...,  0.,  0.,  0.]]),
 array([3, 4, 4, ..., 2, 3, 1]),
 array([4, 1, 3, ..., 1, 4, 1]))

In [14]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [15]:
X_train

array([[-0.30289399, -0.30376871, -0.30022013, ..., -0.04138755,
        -0.04180969, -0.03920918],
       [-0.30289399, -0.30376871, -0.30022013, ..., -0.04138755,
        -0.04180969, -0.03920918],
       [-0.30289399, -0.30376871, -0.30022013, ..., -0.04138755,
        -0.04180969, -0.03920918],
       ..., 
       [-0.30289399, -0.30376871, -0.30022013, ..., -0.04138755,
        -0.04180969, -0.03920918],
       [-0.30289399, -0.30376871, -0.30022013, ..., -0.04138755,
        -0.04180969, -0.03920918],
       [-0.30289399, -0.30376871, -0.30022013, ..., -0.04138755,
        -0.04180969, -0.03920918]])

## Fitting KNN classifier to the training set

In [16]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
model_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski' , p=2)
model_knn.fit(X_train , y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [19]:
y_pred = model_knn.predict(X_test)

In [20]:
y_pred[:5]

array([1, 2, 3, 2, 1])

In [24]:
# saving the model
import pickle
from sklearn.externals import joblib
filename = 'knn_model.pkl'
joblib.dump(model_knn, filename)

['knn_model.pkl']

In [ ]:
# load the model from disk
loaded_model = joblib.load(filename)
score = loaded_model.score(X_test, y_test)
print("Test score: {0:.2f} %".format(100 * score))

Test score: 24.73 %


In [ ]:
Ypredict = loaded_model.predict(X_test) 

In [ ]:
# source for file saving - https://stackabuse.com/scikit-learn-save-and-restore-models/